name: kmahelona
favicon: null
layout_spectrum: 0.12064604042097926
typography_spectrum: 0.21298933611251414
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.10186299122869968
  lightness: 0.457680189749226
  saturation: 0.8563364339061081
  rhythmicContrast: 0.633959949715063
purpose: []
